# configuration of the build stage
FROM node:19-alpine as build
WORKDIR /app
COPY . .
# install dependencies
RUN npm install
# build
RUN npm run build

# slim output image
FROM node:19-alpine as output
WORKDIR /app
COPY --from=build /app/package.json .
COPY --from=build /app/package-lock.json .
COPY --from=build /app/server.ts .
COPY --from=build /app/dist dist/
# install prod dependencies
RUN npm ci --omit dev
# set env variables
ENV PORT 4000
# open port
EXPOSE 4000
CMD ["npx","ts-node","server.ts"]