image: docker:24.0.5

stages:
  - build
  # - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:24.0.5-dind

before_script:
    - docker info

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker compose build
    - docker compose push

# deploy:
#   stage: deploy
#   script:
#     - apt-get update && apt-get install -y sshpass
#     - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd /path/to/your/project && docker-compose pull && docker-compose down && docker-compose up -d"
