image: docker:24.0.5

stages:
  - build
  # - deploy

services:
  - name: docker:24.0.5-dind
    alias: thedockerhost

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://thedockerhost:2375/


before_script:
    - docker info

build:
  stage: build
  only:
    - main
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker compose build
    - docker compose push

# deploy:
#   stage: deploy
#   script:
#     - apt-get update && apt-get install -y sshpass
#     - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd /path/to/your/project && docker-compose pull && docker-compose down && docker-compose up -d"
