version: '3'
services:
  admin_app:
    build: ./admin-app
    # image: docker.gitlab.gwdg.de/m.strzebkowski/lost-in-code/admin_app:latest
  
  api:
    build: ./api
    # image: docker.gitlab.gwdg.de/m.strzebkowski/lost-in-code/api:latest
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
    depends_on:
      - mysql
  
  game:
    build: ./game
    # image: docker.gitlab.gwdg.de/m.strzebkowski/lost-in-code/game:latest
    
  php_executor:
    build: ./php-server
    # image: docker.gitlab.gwdg.de/m.strzebkowski/lost-in-code/php_executor:latest
    
  
  nginx:
    build: ./nginx-proxy
    # image: docker.gitlab.gwdg.de/m.strzebkowski/lost-in-code/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - admin_app
      - api
      - game
      - php_executor

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./lost_in_code.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - ./.env.db
  
volumes:
  mysql_data:
